"use server";

import { revalidatePath, revalidateTag } from "next/cache";
import { redirect } from "next/navigation";
import { requireAdmin } from "@/lib/auth";
import { createAdminClient } from "@/lib/supabase/admin";
import { createServerSupabase } from "@/lib/supabase/server";

export type ActionState = { error?: string; success?: string };
const attempts = new Map<string, { count: number; reset: number }>();
const text = (form: FormData, key: string) => String(form.get(key) || "").trim();
const slugify = (value: string) => value.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

export async function loginAction(_: ActionState, form: FormData): Promise<ActionState> { const identifier = text(form, "identifier").toLowerCase(), password = String(form.get("password") || ""), now = Date.now(), current = attempts.get(identifier); if (current && current.reset > now && current.count >= 5) return { error: "Too many attempts. Wait 15 minutes and try again." }; attempts.set(identifier, current && current.reset > now ? { ...current, count: current.count + 1 } : { count: 1, reset: now + 15 * 60_000 }); if (!identifier || password.length < 8) return { error: "Enter a valid username or email and password." }; try { let email = identifier; if (!identifier.includes("@")) { const admin = createAdminClient(), { data: profile } = await admin.from("profiles").select("id").eq("username", identifier).maybeSingle(); if (!profile) return { error: "Invalid login details." }; const { data } = await admin.auth.admin.getUserById(profile.id); email = data.user?.email || ""; } const supabase = await createServerSupabase(); const { error } = await supabase.auth.signInWithPassword({ email, password }); if (error) return { error: "Invalid login details." }; attempts.delete(identifier); } catch { return { error: "Admin authentication is not configured. Check the Supabase environment variables." }; } redirect("/admin"); }
export async function logoutAction() { const supabase = await createServerSupabase(); await supabase.auth.signOut(); redirect("/admin/login"); }

export async function savePostAction(form: FormData) { await requireAdmin(); const admin = createAdminClient(), id = text(form, "id"), status = text(form, "status"), suppliedDate = text(form, "published_at"); const publishedAt = status === "draft" ? null : suppliedDate ? new Date(suppliedDate).toISOString() : new Date().toISOString(); const payload = { title: text(form, "title"), slug: slugify(text(form, "slug") || text(form, "title")), meta_description: text(form, "meta_description"), seo_title: text(form, "seo_title") || null, featured_image: text(form, "featured_image") || null, featured_image_alt: text(form, "featured_image_alt"), og_image: text(form, "og_image") || null, category: text(form, "category") || "Guides", tags: text(form, "tags").split(",").map((item) => item.trim()).filter(Boolean), author: text(form, "author") || "Figimi Editorial", body: String(form.get("body") || ""), status, published_at: publishedAt }; if (!payload.title || !payload.slug || !payload.body) redirect(`/admin/posts/${id || "new"}?error=required`); const query = id ? admin.from("posts").update(payload).eq("id", id) : admin.from("posts").insert(payload); const { error } = await query; if (error) redirect(`/admin/posts/${id || "new"}?error=${encodeURIComponent(error.message)}`); revalidateTag("posts"); revalidatePath("/blog"); revalidatePath(`/blog/${payload.slug}`); redirect("/admin/posts?saved=1"); }
export async function deletePostAction(form: FormData) { await requireAdmin(); const id = text(form, "id"); if (id) await createAdminClient().from("posts").delete().eq("id", id); revalidateTag("posts"); revalidatePath("/blog"); redirect("/admin/posts?deleted=1"); }

export async function saveToolAction(form: FormData) { await requireAdmin(); const admin = createAdminClient(), slug = text(form, "slug"); let faq: unknown[] = []; try { faq = JSON.parse(String(form.get("faq") || "[]")); } catch { redirect(`/admin/tools/${slug}?error=invalid-faq`); } const payload = { slug, title: text(form, "title"), description: text(form, "description"), intro: String(form.get("intro") || ""), how_to: String(form.get("how_to") || "").split("\n").map((line) => line.trim()).filter(Boolean), faq, seo_title: text(form, "seo_title"), seo_description: text(form, "seo_description"), og_image: text(form, "og_image") || null }; const { error } = await admin.from("tool_pages").upsert(payload); if (error) redirect(`/admin/tools/${slug}?error=${encodeURIComponent(error.message)}`); revalidateTag("tool-pages"); revalidatePath(`/tools/${slug}`); redirect("/admin/tools?saved=1"); }
export async function saveContentAction(form: FormData) { await requireAdmin(); const slug = text(form, "slug"), payload = { slug, title: text(form, "title"), description: text(form, "description"), body: String(form.get("body") || ""), seo_title: text(form, "seo_title") || null, og_image: text(form, "og_image") || null }; const { error } = await createAdminClient().from("content_pages").upsert(payload); if (error) redirect(`/admin/pages/${slug}?error=${encodeURIComponent(error.message)}`); revalidateTag("content-pages"); revalidatePath(`/${slug}`); redirect("/admin/pages?saved=1"); }
export async function saveSettingsAction(form: FormData) { await requireAdmin(); const payload = { id: 1, analytics_id: text(form, "analytics_id"), adsense_client_id: text(form, "adsense_client_id"), google_tag_id: text(form, "google_tag_id"), head_code: String(form.get("head_code") || ""), body_code: String(form.get("body_code") || "") }; const { error } = await createAdminClient().from("site_settings").upsert(payload); if (error) redirect(`/admin/settings?error=${encodeURIComponent(error.message)}`); revalidateTag("site-settings"); revalidatePath("/", "layout"); redirect("/admin/settings?saved=1"); }

export async function uploadMediaAction(form: FormData) { const { user } = await requireAdmin(); const file = form.get("file"); if (!(file instanceof File) || !file.size) redirect("/admin/media?error=file"); if (file.size > 5 * 1024 * 1024 || !["image/jpeg", "image/png", "image/webp", "image/gif"].includes(file.type)) redirect("/admin/media?error=type"); const admin = createAdminClient(), safe = file.name.toLowerCase().replace(/[^a-z0-9._-]+/g, "-").slice(-100), path = `${new Date().toISOString().slice(0, 10)}/${crypto.randomUUID()}-${safe}`; const { error: uploadError } = await admin.storage.from("media").upload(path, file, { contentType: file.type, upsert: false, cacheControl: "31536000" }); if (uploadError) redirect(`/admin/media?error=${encodeURIComponent(uploadError.message)}`); const { data } = admin.storage.from("media").getPublicUrl(path); const cdnBase = process.env.NEXT_PUBLIC_MEDIA_CDN_URL?.replace(/\/$/, ""), url = cdnBase ? `${cdnBase}/${path}` : data.publicUrl; await admin.from("media").insert({ name: file.name, path, url, alt_text: text(form, "alt_text"), mime_type: file.type, size_bytes: file.size, created_by: user.id }); redirect("/admin/media?uploaded=1"); }
export async function deleteMediaAction(form: FormData) { await requireAdmin(); const id = text(form, "id"), path = text(form, "path"), admin = createAdminClient(); if (path) await admin.storage.from("media").remove([path]); if (id) await admin.from("media").delete().eq("id", id); redirect("/admin/media?deleted=1"); }
