import type { ToolDefinition } from "@/types";

type Faq = { question: string; answer: string };

const sharedFileFaq = (name: string, output: string): Faq[] => [
  { question: `Is the ${name} free?`, answer: "Yes. You can use this converter without creating an account. Fair-use and 20 MB upload limits protect service availability." },
  { question: "What happens to my uploaded file?", answer: "Files are processed only to complete your request and are automatically removed from temporary storage within one hour." },
  { question: `How accurate is the ${output} output?`, answer: "Simple documents preserve their structure well. Complex layouts, embedded fonts, scans, and advanced formulas may require a quick review after conversion." },
];

const converter = (slug: string, name: string, shortDescription: string, accept: string, output: string, keywords: string[], description?: string, faq?: Faq[]): ToolDefinition => ({
  slug, name, shortDescription, accept, output, keywords, category: "File converters", kind: "converter",
  description: description || `${name} converts your document in a secure server-side process. Upload a file up to 20 MB, follow conversion progress, and download the result. The page explains format limitations before you start, and temporary files are deleted automatically within one hour.`,
  faq: faq || sharedFileFaq(name, output),
});

export const tools: ToolDefinition[] = [
  { slug: "word-counter", name: "Word Counter", shortDescription: "Analyze writing and get statistics about words, characters, sentences, paragraphs, reading time, and keyword density.", category: "Text tools", kind: "word-counter", keywords: ["word count", "reading time", "keyword density"], description: "Analyze your writing and get statistics in your browser. Live data helps you assess readability and keyword density to show repeated keywords. There is no need to send your draft to the server.", faq: [{ question: "Is my text uploaded somewhere?", answer: "No. All text analysis is done in your browser." }, { question: "How do you calculate reading time?", answer: "This is done by estimating the average reading age of 200 words a minute." }] },
  { slug: "character-counter", name: "Character Counter", shortDescription: "Live character counts and totals. Count letters and characters with and without spaces. Also count words and lines.", category: "Text tools", kind: "character-counter", keywords: ["character count", "letter counter", "social media length"], description: "Makes sure you stay within the character limit for posts, messages, snips and more. Our tool counts every character and reports characters without whitespace.", faq: [{ question: "Are symbols and punctuation counted?", answer: "Yes. They are characters too." }, { question: "Is my text saved?", answer: "No. All counting is done in the browser." }] },
  { slug: "website-word-counter", name: "Web Page Word Counter", shortDescription: "Submit a public URL to find the word count and estimate reading time.", category: "Text tools", kind: "website-counter", keywords: ["website word count", "page analyzer", "URL word counter"], description: "Gather the readable text for editorial research from a public HTML page. We block private addresses, pages that are too large, and redirect chains to protect the service.", faq: [{ question: "Can it read private pages?", answer: "No. Only public HTTP and HTTPS pages are available." }, { question: "Why can totals differ?", answer: "Some text can be JavaScript-rendered or hidden, and that can alter visible totals." }] },
  { slug: "auto-capitalize", name: "Auto Capitalize Sentences", shortDescription: "Upper case, lower case, title case, and fix case for complete sentences.", category: "Text tools", kind: "capitalize", keywords: ["sentence case", "title case", "capitalize text"], description: "Sentence, title, upper, and lower modes help you clean up casing. View the original, copy the result, or create a downloadable UTF-8 text file of your result.", faq: [{ question: "Does it recognize names?", answer: "No, since proper nouns are beyond automatic rules." }, { question: "Can I download the result?", answer: "Yes, as a plain UTF-8 text file." }] },
  { slug: "compare-text", name: "Compare Text", shortDescription: "Compare two texts to show additions, deletions, and unchanged text.", category: "Text tools", kind: "compare", keywords: ["text diff", "compare documents", "difference checker"], description: "Compare two texts, revisions, and additions at the word level. Added text is colored differently from removed text. The original text stays in the browser.", faq: [{ question: "Is it private?", answer: "Yes. We only do the word diff in your browser." }, { question: "What kind of diff is this?", answer: "This is a word level LCS diff." }] },
  converter("pdf-to-word", "PDF to Word Converter", "PDF files to DOCX files.", ".pdf", "DOCX", ["PDF to DOCX", "editable PDF"], "Want text from a PDF to a Word file? This will help. Note: PDF page images, PDF complex formats, and visual elements will need your own review to be updated.", [{ question: "What happens to my files?", answer: "After processing, we delete your files and no later than 1 hour." }, { question: "What if my PDF is a scanned book?", answer: "PDF scans will need you to OCR before we can help." }]),
  converter("word-to-pdf", "Word to PDF Converter", "Create a portable PDF from a DOC or DOCX file.", ".doc,.docx", "PDF", ["DOCX to PDF", "Word PDF"], "Not a lot of people know that Word documents can actually be easily converted into Portable Document Format (PDF) files simply by using a server-side office engine. With all the different font styles and layouts that are involved in Word documents, the results may vary, so make sure to observe the result before making use of the file.", [{ question: "Is this service free to use?", answer: "Yes, as long as you follow the file size limit and fair use." }, { question: "For how long are files kept in your system?", answer: "They are deleted immediately after processing or the latest within one hour." }]),
  converter("pdf-to-png", "PDF to PNG Converter", "Render PDF pages as crisp PNG images.", ".pdf", "ZIP of PNG images", ["PDF image", "PDF PNG"], "Have you ever needed to extract images from a PDF file? Look no further! You can convert a PDF file and extract an image of each page by following these instructions.", [{ question: "I have a multi-page PDF file. How will you deliver the converted files?", answer: "You will receive a ZIP file which contains all the PNG images of each page of the PDF file." }, { question: "Do you care about the privacy of your documents?", answer: "Yes, all temporary files will be automatically deleted from our system within one hour." }]),
  converter("pdf-to-jpg", "PDF to JPG Converter", "PDF pages converted to compact JPG images.", ".pdf", "ZIP of JPG images", ["PDF JPG", "PDF image"], "PDF pages converted to compressed JPG images are easy to share and view on the web. Multi-page documents are returned in a ZIP file.", [{ question: "In what format are the JPGs received?", answer: "JPG files are compressed in a ZIP file." }, { question: "Does quality compression change?", answer: "JPG files are always compressed with lossy quality." }]),
  converter("pdf-to-excel", "PDF to Excel Converter", "PDF text is placed in the XLSX file.", ".pdf", "XLSX", ["PDF XLSX", "extract PDF table"], "Selectable text and spacing-separated columns will be converted to the XLSX file. Review the results for complex spacing-separated tables.", [{ question: "Do I need OCR for this?", answer: "Only for scanned documents with images." }, { question: "Will formatting be the same?", answer: "Merged cells and complex layouts may require additional formatting." }]),
  converter("excel-to-pdf", "Excel to PDF Converter", "Export XLS or XLSX files to PDF.", ".xls,.xlsx", "PDF", ["XLSX PDF", "spreadsheet PDF"], "Use an Office engine to export your Excel Workbook as a PDF for easy distribution or viewing!", [{ question: "Are my formulas recalculated?", answer: "Our Office engine may recalculate formulas for your file." }, { question: "Are my uploads stored?", answer: "No! All temporary files are deleted within 1 hour." }]),
  converter("ppt-to-pdf", "PPT to PDF Converter", "Export your PowerPoint slides as a PDF.", ".ppt,.pptx", "PDF", ["PPTX PDF", "slides PDF"], "Export your PPT or PPTX files as a PDF. Because a PDF is a static format, animating or layering things on top of one another are not possible, although slides will look as they do in PowerPoint as much as possible.", [{ question: "Will my animations show up?", answer: "No, a PDF is a static format and will not show animations." }, { question: "Will my fonts show up as intended?", answer: "Fonts that are not available may be substituted by our servers." }]),
  converter("pdf-to-ppt", "PDF to PPT Converter", "Turn PDF pages into PowerPoint slides.", ".pdf", "PPTX", ["PDF PPTX", "PDF slides"]),
  converter("jpg-to-pdf", "JPG to PDF Converter", "Combine JPG images into a PDF.", ".jpg,.jpeg", "PDF", ["JPG PDF", "image PDF"], "Create a PDF with up to twenty JPG images while oversized images are resized to fit PDF boundaries.", [{ question: "How many JPG images can I upload?", answer: "20 maximum." }, { question: "Will combining the JPG images into a PDF reduce the quality?", answer: "No, the quality JPG images will be embedded into the PDF without compression." }]),
  converter("png-to-pdf", "PNG to PDF Converter", "Convert multiple single or batch PNG files to PDF.", ".png", "PDF", ["PNG PDF", "image PDF"], "Convert 20 PNG files to PDF. Our online tool works to optimize larger page sizes as well as maintain file transparency.", [{ question: "How many PNG files can I combine?", answer: "You may combine up to 20 files." }, { question: "How long will files be stored?", answer: "Files will be deleted within 1 hour of processing, usually much sooner." }]),
  { slug: "color-wheel", name: "Color Wheel", shortDescription: "Pick colors and generate complementary, analogous, and triadic palettes.", category: "Design tools", kind: "color-wheel", keywords: ["color picker", "HEX", "palette generator"], description: "The interactive Color Wheel turns a visual color choice into production-ready HEX, RGB, and HSL values. Generate harmonious palettes using complementary, analogous, triadic, or monochromatic relationships and copy any swatch with one click.", faq: [{ question: "What is a complementary color?", answer: "It sits opposite the selected color on the hue wheel and creates strong visual contrast." }, { question: "Which format should I use for the web?", answer: "HEX, RGB, and HSL all work in modern CSS. HSL is often easiest when adjusting hue, saturation, or lightness." }, { question: "Are palettes saved?", answer: "No. Palette generation runs locally; copy the values you want to keep." }] },
  { slug: "random-color-generator", name: "Random Color Generator", shortDescription: "Choose random colors and generate swatches with HEX, RGB, HSL values.", category: "Design tools", kind: "random-color", keywords: ["random color", "color generator", "HEX generator", "random palette"], description: "Design with random colors! Great for design ideas or writing prompts. Pick a set of swatches, lock the swatches you want to keep and get ready-to-use HEX, RGB, and HSL values. Everything is done in your browser.", faq: [{ question: "How does shuffling colors work?", answer: "Each color channel is populated with a value for an even distribution of colors and uses a securely seeded random value." }, { question: "How do I keep a color?", answer: "Lock the color swatch to keep it, the un-locked swatches will be changed." }] },
  { slug: "image-to-text", name: "Image to Text Converter", shortDescription: "Scan images and screenshots to extract editable text using our in-browser OCR.", category: "Text tools", kind: "image-to-text", keywords: ["image to text", "OCR", "extract text from image", "picture to text"], description: "Use OCR in your browser to extract editable text from images and screenshots. The image is never uploaded to our server.", faq: [{ question: "Is my image uploaded?", answer: "No. The text recognition happens in your browser so the image stays on your device." }, { question: "Why is some text extracted incorrectly?", answer: "There are many reasons as to why the extracted text is not accurate. For example, the image could have a low resolution, contain handwriting, or have a noisy background. To get the correct text, use images that are clear and straight." }] },
];

export const toolBySlug = (slug: string) => tools.find((tool) => tool.slug === slug);
export const toolCategories = ["Text tools", "File converters", "Design tools"] as const;
