import type { ToolDefinition } from "@/types";

const sharedFileFaq = (name: string, output: string) => [
  { question: `Is the ${name} free?`, answer: "Yes. You can use this converter without creating an account. Fair-use and 20 MB upload limits protect service availability." },
  { question: "What happens to my uploaded file?", answer: "Files are processed only to complete your request and are automatically removed from temporary storage within one hour." },
  { question: `How accurate is the ${output} output?`, answer: "Simple documents preserve their structure well. Complex layouts, embedded fonts, scans, and advanced formulas may require a quick review after conversion." },
];

const converter = (slug: string, name: string, shortDescription: string, accept: string, output: string, keywords: string[]): ToolDefinition => ({
  slug, name, shortDescription, accept, output, keywords, category: "File converters", kind: "converter",
  description: `${name} converts your document in a secure server-side process. Upload a file up to 20 MB, follow conversion progress, and download the result. The page explains format limitations before you start, and temporary files are deleted automatically within one hour.`,
  faq: sharedFileFaq(name, output),
});

export const tools: ToolDefinition[] = [
  { slug: "word-counter", name: "Word Counter", shortDescription: "Count words, characters, sentences, paragraphs, reading time, and keyword density.", category: "Text tools", kind: "word-counter", keywords: ["word count", "reading time", "keyword density"], description: "The Word Counter gives writers an immediate, private analysis of text directly in the browser. Beyond a basic word total, it measures characters, sentences, paragraphs, estimated reading time, and frequently used keywords so you can shape content for readers, assignments, or search results.", faq: [{ question: "How is reading time calculated?", answer: "Reading time uses an average adult reading speed of about 200 words per minute and rounds up to the nearest minute." }, { question: "Does this tool upload my text?", answer: "No. The text analysis runs in your browser and is not sent to our server." }, { question: "What counts as a word?", answer: "A word is a sequence separated by whitespace. Punctuation around a word is ignored for keyword analysis." }] },
  { slug: "character-counter", name: "Character Counter", shortDescription: "See live character totals with and without spaces, plus words and lines.", category: "Text tools", kind: "character-counter", keywords: ["character count", "letter counter", "social media length"], description: "Character Counter helps you fit text into form fields, headlines, snippets, messages, and platform limits. Results update as you type and include totals with spaces, without spaces, words, and lines. Everything stays in your browser.", faq: [{ question: "Are punctuation marks included?", answer: "Yes. The total character count includes letters, numbers, punctuation, symbols, and spaces." }, { question: "Are line breaks characters?", answer: "Line breaks are included in the complete character total and separately reflected in the line count." }, { question: "Is my text stored?", answer: "No. Counting happens locally in your browser." }] },
  { slug: "website-word-counter", name: "Web Page Word Counter", shortDescription: "Enter a public URL to estimate its visible word count and reading time.", category: "Text tools", kind: "website-counter", keywords: ["website word count", "page analyzer", "URL word counter"], description: "The Web Page Word Counter fetches a publicly accessible page and analyzes readable text after removing scripts, styles, and markup. It is useful for editorial research and content planning, but dynamic or login-protected pages may not expose all text.", faq: [{ question: "Can it count any website?", answer: "It supports public HTTP and HTTPS pages. Private networks, local addresses, login-protected pages, and very large responses are blocked for security." }, { question: "Why might the total differ from what I see?", answer: "JavaScript-rendered text, navigation, cookie notices, and hidden accessibility content can affect totals." }, { question: "Do you store submitted URLs?", answer: "URLs are used only for the request and are not added to a marketing profile." }] },
  { slug: "auto-capitalize", name: "Auto Capitalize Sentences", shortDescription: "Fix sentence capitalization or convert text to title, upper, or lower case.", category: "Text tools", kind: "capitalize", keywords: ["sentence case", "title case", "capitalize text"], description: "Auto Capitalize cleans inconsistent casing while leaving your original text available for comparison. Choose sentence case, title case, uppercase, or lowercase, then copy the result or download a plain-text file.", faq: [{ question: "Does sentence case change names?", answer: "Automatic rules cannot identify every proper noun, so review names and specialist terms after conversion." }, { question: "Which title-case style is used?", answer: "The tool capitalizes major words and keeps common short articles, conjunctions, and prepositions lowercase except at the start or end." }, { question: "Can I download the result?", answer: "Yes. Use the download button to save a UTF-8 text file." }] },
  { slug: "compare-text", name: "Compare Text", shortDescription: "Compare two passages and highlight additions, removals, and unchanged words.", category: "Text tools", kind: "compare", keywords: ["text diff", "compare documents", "difference checker"], description: "Compare Text provides a clear word-level diff for drafts, revisions, and copied passages. Additions and removals are color-coded in a readable result while your source text remains in the two side-by-side editors.", faq: [{ question: "What type of comparison is used?", answer: "The browser computes a word-level longest-common-subsequence diff, which is easy to read for prose and short documents." }, { question: "Can it compare large documents?", answer: "It is optimized for normal articles and drafts. Very large texts may take longer because all work happens in your browser." }, { question: "Is compared text uploaded?", answer: "No. Comparison is performed locally." }] },
  converter("pdf-to-word", "PDF to Word Converter", "Turn a PDF into an editable DOCX document.", ".pdf", "DOCX", ["PDF to DOCX", "editable PDF"]),
  converter("word-to-pdf", "Word to PDF Converter", "Create a portable PDF from a DOC or DOCX file.", ".doc,.docx", "PDF", ["DOCX to PDF", "Word PDF"]),
  converter("pdf-to-png", "PDF to PNG Converter", "Render PDF pages as crisp PNG images.", ".pdf", "ZIP of PNG images", ["PDF image", "PDF PNG"]),
  converter("pdf-to-jpg", "PDF to JPG Converter", "Render PDF pages as compact JPG images.", ".pdf", "ZIP of JPG images", ["PDF JPG", "PDF image"]),
  converter("pdf-to-excel", "PDF to Excel Converter", "Extract readable PDF text into an XLSX workbook.", ".pdf", "XLSX", ["PDF XLSX", "extract PDF table"]),
  converter("excel-to-pdf", "Excel to PDF Converter", "Export XLS or XLSX spreadsheets as PDF.", ".xls,.xlsx", "PDF", ["XLSX PDF", "spreadsheet PDF"]),
  converter("ppt-to-pdf", "PPT to PDF Converter", "Export PowerPoint presentations as PDF.", ".ppt,.pptx", "PDF", ["PPTX PDF", "slides PDF"]),
  converter("pdf-to-ppt", "PDF to PPT Converter", "Turn PDF pages into PowerPoint slides.", ".pdf", "PPTX", ["PDF PPTX", "PDF slides"]),
  converter("jpg-to-pdf", "JPG to PDF Converter", "Combine one or more JPG images into a PDF.", ".jpg,.jpeg", "PDF", ["JPG PDF", "image PDF"]),
  converter("png-to-pdf", "PNG to PDF Converter", "Combine one or more PNG images into a PDF.", ".png", "PDF", ["PNG PDF", "image PDF"]),
  { slug: "color-wheel", name: "Color Wheel", shortDescription: "Pick colors and generate complementary, analogous, and triadic palettes.", category: "Design tools", kind: "color-wheel", keywords: ["color picker", "HEX", "palette generator"], description: "The interactive Color Wheel turns a visual color choice into production-ready HEX, RGB, and HSL values. Generate harmonious palettes using complementary, analogous, triadic, or monochromatic relationships and copy any swatch with one click.", faq: [{ question: "What is a complementary color?", answer: "It sits opposite the selected color on the hue wheel and creates strong visual contrast." }, { question: "Which format should I use for the web?", answer: "HEX, RGB, and HSL all work in modern CSS. HSL is often easiest when adjusting hue, saturation, or lightness." }, { question: "Are palettes saved?", answer: "No. Palette generation runs locally; copy the values you want to keep." }] },
  { slug: "random-color-generator", name: "Random Color Generator", shortDescription: "Generate random colors and full swatch sets with instant HEX, RGB, and HSL values.", category: "Design tools", kind: "random-color", keywords: ["random color", "color generator", "HEX generator", "random palette"], description: "The Random Color Generator instantly creates fresh colors for design experiments, brand exploration, and creative prompts. Shuffle a whole set of swatches, lock the ones you like, and copy production-ready HEX, RGB, and HSL values with one click. Everything runs in your browser, so no selection is ever sent to a server.", faq: [{ question: "How are the colors generated?", answer: "Each swatch uses a cryptographically seeded random value for its red, green, and blue channels, giving an even spread across the full color space." }, { question: "Can I keep a color I like while shuffling?", answer: "Yes. Lock any swatch and it stays fixed while the remaining swatches regenerate on the next shuffle." }, { question: "Which value should I copy for CSS?", answer: "HEX, RGB, and HSL all work in modern CSS. Click any value to copy it instantly." }] },
  { slug: "image-to-text", name: "Image to Text Converter", shortDescription: "Extract editable text from images and screenshots with in-browser OCR.", category: "Text tools", kind: "image-to-text", keywords: ["image to text", "OCR", "extract text from image", "picture to text"], description: "The Image to Text Converter uses optical character recognition (OCR) to pull readable, editable text out of photos, screenshots, and scanned pages. Recognition runs entirely in your browser, so the image is never uploaded to our server. Drop a PNG, JPG, or WebP, watch the progress, then copy or download the extracted text.", faq: [{ question: "Is my image uploaded to a server?", answer: "No. Optical character recognition runs locally in your browser using a downloaded engine, so the image data stays on your device." }, { question: "Which languages are supported?", answer: "The tool recognizes English-language text by default and works best on clear, high-contrast images." }, { question: "Why is some text inaccurate?", answer: "Low resolution, handwriting, unusual fonts, skew, and noisy backgrounds reduce accuracy. Use a sharp, well-lit, straight image for the best results and review the output." }] },
];

export const toolBySlug = (slug: string) => tools.find((tool) => tool.slug === slug);
export const toolCategories = ["Text tools", "File converters", "Design tools"] as const;
